import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "./components/NavBar";
import { AccountBox, CreditCard, Description, Folder, NoteAdd, Person } from "@mui/icons-material";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "./theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const drawerContent = [
    { text: "Clientes",             icon: <Person />,       href: "/customers" },
    { text: "Planos",               icon: <Description />,  href: "/plans" },
    { text: "Serviços Adicionais",  icon: <NoteAdd />,      href: "/services" },
    { text: "Pacotes",              icon: <Folder />,       href: "/packages" },
    { text: "Assinaturas",          icon: <AccountBox />,   href: "/subscriptions" },
    { text: "Cobranças",            icon: <CreditCard />,   href: "/bills"} ,
  ]

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <NavBar drawerContent={drawerContent}>{children}</NavBar>
        </ThemeProvider>
      </body>
    </html>
  );
}
